---
# 1. Install Docker
- name: Install Docker
  become: yes
  shell: curl -fsSL https://get.docker.com | sh
  args:
    creates: /usr/bin/docker

# 2. Start Docker
- name: Start Docker
  become: yes
  service:
    name: docker
    state: started
    enabled: true

# 3. Add ubuntu user to docker group
- name: Add ubuntu user to docker group
  become: yes
  user:
    name: ubuntu
    groups: docker
    append: yes

# ✅ IMPORTANT
- name: Reset SSH connection
  meta: reset_connection

# 4. Ensure plugin directory
- name: Ensure cli-plugins directory exists
  become: yes
  file:
    path: /usr/lib/docker/cli-plugins
    state: directory
    mode: '0755'

# 5. Install Docker Compose plugin
- name: Install Docker Compose plugin
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
    dest: /usr/lib/docker/cli-plugins/docker-compose
    mode: '0755'

# 6. Create project directory
- name: Create project directory
  file:
    path: "/home/ubuntu/pro-stack"
    state: directory
    mode: '0755'

# 7. Deploy files
- name: Deploy Docker Compose Template
  template:
    src: docker-compose.yml.j2
    dest: "/home/ubuntu/pro-stack/docker-compose.yml"

- name: Deploy Nginx Configuration
  template:
    src: nginx.conf.j2
    dest: "/home/ubuntu/pro-stack/nginx.conf"

# 8. Stop old containers (optional but clean)
- name: Stop existing containers
  become: yes
  shell: docker compose down
  args:
    chdir: "/home/ubuntu/pro-stack"
  ignore_errors: yes

# 9. Start new containers
- name: Start the Pro Stack
  become: yes
  shell: docker compose up -d --pull always
  args:
    chdir: "/home/ubuntu/pro-stack"

# 8. Stop old containers
- name: Stop existing containers
  shell: docker compose down
  args:
    chdir: "/home/ubuntu/pro-stack"
  ignore_errors: yes

# 9. Start new containers
- name: Start the Pro Stack
  shell: docker compose up -d --pull always
  args:
    chdir: "/home/ubuntu/pro-stack"

# 10. Server Cleanup (Zaroori Step)
- name: Prune old Docker images to save space
  shell: docker image prune -af --filter "until=24h"
  # Ye un images ko delete karega jo 24 ghante se purani hain aur use nahi ho rahi
