name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: shivendra01
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t shivendra01/micro-web-optimized:latest .
          docker push shivendra01/micro-web-optimized:latest

      - name: Write SSH Key
        run: |
          cat <<EOF > id_rsa
          ${{ secrets.EC2_SSH_KEY }}
          EOF
          chmod 600 id_rsa
         ssh-keyscan -H 34.225.194.175 >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          # Step A: Install Ansible and Docker Collection
          pip install ansible
          ansible-galaxy collection install community.docker

          # Step B: Create temporary vault pass file from GitHub Secrets
          echo "${{ secrets.VAULT_PASSWORD }}" > .vault_pass
          chmod 600 .vault_pass

          # Step C: Execute Playbook
          ansible-playbook -i inventory.ini full-cycle.yml \
          --private-key id_rsa \
          -u ubuntu \
          --vault-password-file .vault_pass \
          -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no'" \
          -e "docker_image=shivendra01/micro-web-optimized:latest"
